# Generated by Django 5.2.7 on 2025-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swaram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
