# Generated by Django 5.2.7 on 2025-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swaram', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
