# Generated by Django 5.2.7 on 2025-11-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Swaram', '0005_user_district_user_email_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
