# Generated by Django 5.2.7 on 2025-11-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Swaram', '0007_intern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='name',
        ),
    ]
