# Generated by Django 5.2.7 on 2025-11-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Swaram', '0008_remove_intern_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='folder',
            new_name='folder_name',
        ),
        migrations.AlterModelTable(
            name='intern',
            table='Swaram_intern',
        ),
    ]
